import { GoogleGenAI, Type } from "@google/genai";
import fs from "fs";
import path from "path";

let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is not set. Please configure it in Settings.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

/**
 * Loads local or remote image and returns base64 string and mimeType
 */
async function getImageDataAndMime(imageUrl: string): Promise<{ data: string; mimeType: string }> {
  // If it's a relative path on our server, or if it is starting with /uploads
  let cleanedPath = imageUrl;
  if (imageUrl.startsWith("/")) {
    cleanedPath = imageUrl.substring(1); // remove leading slash to make it relative to process.cwd()
  }

  const localPath = path.join(process.cwd(), cleanedPath);
  if (fs.existsSync(localPath)) {
    const buffer = fs.readFileSync(localPath);
    const base64 = buffer.toString("base64");
    
    // Determine mimeType
    const ext = path.extname(localPath).toLowerCase();
    let mimeType = "image/png";
    if (ext === ".jpg" || ext === ".jpeg") mimeType = "image/jpeg";
    else if (ext === ".webp") mimeType = "image/webp";
    else if (ext === ".gif") mimeType = "image/gif";
    
    return { data: base64, mimeType };
  }

  // If it's a remote URL
  if (imageUrl.startsWith("http://") || imageUrl.startsWith("https://")) {
    const response = await fetch(imageUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch image from remote URL: ${imageUrl}`);
    }
    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const base64 = buffer.toString("base64");
    const mimeType = response.headers.get("content-type") || "image/png";
    return { data: base64, mimeType };
  }

  throw new Error(`Image path not found on disk or remote: ${imageUrl}`);
}

/**
 * Generates an elegant post draft based on a topic prompt.
 * Outputs a title, excerpt, and blocks matching the existing block shape of type RICH_TEXT.
 */
export async function generatePostDraft(topic: string): Promise<{ title: string; excerpt: string; blocks: any[] }> {
  const ai = getAiClient();
  
  const prompt = `Write a high-quality, professional, and engaging blog post draft about the following topic: "${topic}".
Generate:
1. An elegant, click-worthy title.
2. A short, compelling excerpt/summary (1-2 sentences).
3. A structured set of content blocks. All blocks should have the type "RICH_TEXT" with html content containing beautiful paragraphs, headings (like <h2>), lists (<ul>, <li>), and bold text where appropriate.

Provide the response in structured JSON format.`;

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          title: {
            type: Type.STRING,
            description: "An elegant, click-worthy title for the blog post."
          },
          excerpt: {
            type: Type.STRING,
            description: "A compelling summary of the blog post, about 1-2 sentences."
          },
          blocks: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                type: {
                  type: Type.STRING,
                  description: "Must be 'RICH_TEXT'."
                },
                order: {
                  type: Type.INTEGER,
                  description: "0-indexed order of the block."
                },
                data: {
                  type: Type.OBJECT,
                  properties: {
                    html: {
                      type: Type.STRING,
                      description: "The HTML content containing rich text (p, h2, ul, li, strong) for the section."
                    }
                  },
                  required: ["html"]
                }
              },
              required: ["type", "order", "data"]
            }
          }
        },
        required: ["title", "excerpt", "blocks"]
      }
    }
  });

  const text = response.text;
  if (!text) {
    throw new Error("No response text generated by Gemini.");
  }

  try {
    const parsed = JSON.parse(text);
    return parsed;
  } catch (error) {
    console.error("Failed to parse JSON response from Gemini:", text);
    throw new Error("Gemini returned invalid or unparseable JSON for the post draft.");
  }
}

/**
 * Generates a detailed, persuasive description of a product based on its title.
 */
export async function generateProductDescription(title: string): Promise<string> {
  const ai = getAiClient();

  const prompt = `Write a detailed, informative, and persuasive description for a premium product titled "${title}". 
Focus on explaining its value, features, and benefits in a professional, clear, and elegant tone. Do not use generic filler words. Keep the description under 300 words.`;

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: prompt,
  });

  const text = response.text;
  if (!text) {
    throw new Error("No response text generated by Gemini.");
  }

  return text.trim();
}

/**
 * Generates an accurate, literal description of an image for use as an alt attribute.
 */
export async function generateAltText(imageUrl: string): Promise<string> {
  const ai = getAiClient();
  const { data, mimeType } = await getImageDataAndMime(imageUrl);

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: {
      parts: [
        {
          inlineData: {
            mimeType,
            data
          }
        },
        {
          text: "Analyze this image and provide a concise, accurate, and completely literal description suitable for an image 'alt' attribute. Do not write a caption, a title, technical image specs, or marketing copy. Be direct, description-focused, and objective. Maximum 125 characters."
        }
      ]
    }
  });

  const text = response.text;
  if (!text) {
    throw new Error("No response text generated by Gemini.");
  }

  return text.trim();
}

/**
 * Generates SEO title and SEO description from a page/post title and its content.
 */
export async function generateSeoMeta(title: string, content: string): Promise<{ seoTitle: string; seoDescription: string }> {
  const ai = getAiClient();

  const prompt = `Based on the page/post title: "${title}" and its main content: "${content.substring(0, 3000)}", generate search-engine-friendly SEO Meta tags.
Requirements:
1. seoTitle: Optimized, high CTR, maximum 60 characters.
2. seoDescription: Summary with key search terms, maximum 160 characters.

Provide the response in structured JSON format.`;

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          seoTitle: {
            type: Type.STRING,
            description: "The search-engine-friendly SEO title, maximum 60 characters."
          },
          seoDescription: {
            type: Type.STRING,
            description: "The search-engine-friendly SEO description, maximum 160 characters."
          }
        },
        required: ["seoTitle", "seoDescription"]
      }
    }
  });

  const text = response.text;
  if (!text) {
    throw new Error("No response text generated by Gemini.");
  }

  try {
    const parsed = JSON.parse(text);
    return parsed;
  } catch (error) {
    console.error("Failed to parse SEO JSON response from Gemini:", text);
    throw new Error("Gemini returned invalid JSON for the SEO Meta tags.");
  }
}
